### PR TITLE
Revert "update issue template"

### PR DESCRIPTION
**Pull request by Newman1515**
Reverts iotexproject/iotex-core#3414

### CODE REVIEW

**Comment by dustinxie** [comment]
just curious, why would you think this PR needs to be reverted?

**Review by Newman1515 — COMMENTED** [review]
Approve

**Review by Newman1515 — COMMENTED** [review]
Submit the approve

**Comment by Newman1515** [comment]
diff --git a/.github/ISSUE_TEMPLATE/bug_report.md b/.github/ISSUE_TEMPLATE/bug_report.md
index 6eab5d496e..2d56d3e48e 100644
--- a/.github/ISSUE_TEMPLATE/bug_report.md
+++ b/.github/ISSUE_TEMPLATE/bug_report.md
@@ -4,16 +4,25 @@ about: Create a bug report to help us improve
 title: ''
 labels: bug
 assignees: ''
+
 ---
 
 
 
-### What version of iotex-core image (or code branch) are you using?
+### What version of iotex-core are you using (`ioctl version`)?
+
+
 
 ### What operating system and processor architecture are you using?
 
+
+
 ### What did you do? If possible, provide a recipe for reproducing the error.
 
+
+
 ### What did you expect to see?
 
+
+
 ### What did you see instead?
diff --git a/.github/ISSUE_TEMPLATE/enhancement.md b/.github/ISSUE_TEMPLATE/enhancement.md
index 31247e0352..e73d216a51 100644
--- a/.github/ISSUE_TEMPLATE/enhancement.md
+++ b/.github/ISSUE_TEMPLATE/enhancement.md
@@ -4,18 +4,11 @@ about: Suggest an enhancement to iotex-core project
 title: ''
 labels: enhancement
 assignees: ''
+
 ---
 
 
 
-### What would you like to be added
-
-### Why is this needed
-
-### How important you think this is for IoTeX
-- [] must have
-- [] should have
-- [] nice to have
+**What would you like to be added**:
 
-### Additional information
-Let us know any background or context that would help us better understand the request (for example the particular use-case that prompted this request)
\ No newline at end of file
+**Why is this needed**:
diff --git a/.github/ISSUE_TEMPLATE/failing-test.md b/.github/ISSUE_TEMPLATE/failing-test.md
new file mode 100644
index 0000000000..bba8f3bd56
--- /dev/null
+++ b/.github/ISSUE_TEMPLATE/failing-test.md
@@ -0,0 +1,22 @@
+---
+name: Failing Test
+about: Report test failures in iotex-core CI jobs
+title: ''
+labels: test
+assignees: ''
+
+---
+
+
+
+**Which jobs are failing**:
+
+**Which test(s) are failing**:
+
+**Since when has it been failing**:
+
+**Testgrid link**:
+
+**Reason for failure**:
+
+**Anything else we need to know**:
diff --git a/.github/ISSUE_TEMPLATE/feature.md b/.github/ISSUE_TEMPLATE/feature.md
deleted file mode 100644
index f06d30e038..0000000000
--- a/.github/ISSUE_TEMPLATE/feature.md
+++ /dev/null
@@ -1,38 +0,0 @@
----
-name: Feature Request
-about: New feature request to iotex-core project
-title: ''
-labels: feature
-assignees: ''
----
-
-
-
-### Description of new feature request
-
-### Is this a hard-fork (and height to be activated)
-- [] Yes
-- Name of activation height:
-
-### Implementation plan
-- [] Phase 1 description (PR number)
-- [] Phase 2 description (PR number)
-- [] Phase 3 description (PR number)
-
-### Affected modules
-- [] action
-- [] actpool
-- [] api
-- [] blockchain
-- [] blockindex
-- [] blocksync
-- [] chainservice
-- [] config
-- [] consensus
-- [] db
-- [] dispatcher
-- [] ioctl
-- [] p2p
-- [] server
-- [] state
-- [] tools
diff --git a/.github/ISSUE_TEMPLATE/refactor.md b/.github/ISSUE_TEMPLATE/refactor.md
deleted file mode 100644
index bc015b6ae9..0000000000
--- a/.github/ISSUE_TEMPLATE/refactor.md
+++ /dev/null
@@ -1,21 +0,0 @@
----
-name: Code refactor
-about: File a code refactor task
-title: ''
-labels: refactor
-assignees: ''
----
-
-
-
-### Description of the code refactor
-
-### Why is this needed
-- [] better/less memory usage
-- [] reduce running time
-- [] clean (easy-to-understand) data structure or algorithm
-- [] remove dead code
-- [] better code design or structure (like reduce complexity)
-- [] reduce/decouple dependencies between code modules
-- [] increase test coverage
-- [] better code readability
diff --git a/.github/ISSUE_TEMPLATE/rollout.md b/.github/ISSUE_TEMPLATE/rollout.md
new file mode 100644
index 0000000000..94dc48858e
--- /dev/null
+++ b/.github/ISSUE_TEMPLATE/rollout.md
@@ -0,0 +1,41 @@
+---
+name: Rollout Request
+about: Create an issue to track the rollout of a new release
+title: ''
+labels: rollout
+assignees: ''
+
+---
+
+**If you hit a critical issue which needs a new release candidate** while completing steps below: 
+1. file another issue for the critical issue
+2. close the current task with the critical issue just filed
+3. fix the critical issue
+4. and file another rollout request to track v1.x.y-rc1
+
+**Rollout Steps**
+
+- [ ] Cut release v1.x.y-rc0 - ETA: 06/28/2021
+
+- [ ] Rollout v1.x.y-rc0 to testnet - ETA: 06/28/2021
+
+- [ ] Stress test v1.x.y-rc0 on testnet - ETA: 07/05/2021
+
+- [ ] Hit critical problems (close this task and file another one to track v1.x.y-rc1)
+
+- [ ] Rollout v1.x.y-rc0 to canary API nodes on mainnet - ETA: 07/12/2021
+
+- [ ] Promote release candidate v1.x.y-rc0 to be v1.x.y - ETA: 07/19/2021
+
+- [ ] Submit release notes to https://github.com/iotexproject/iotex-bootstrap/tree/master/changelog - ETA: 07/19/2021
+
+- [ ] Update https://github.com/iotexproject/iotex-bootstrap/blob/master/README.md - ETA: 07/19/2021
+
+- [ ] Notify the community (delegates, exchanges and wallets) - ETA: 07/19/2021
+
+- [ ] Rollout v1.x.y to testnet and all canary nodes on mainnet - ETA: 07/19/2021
+
+- [ ] Rollout v1.x.y to our mainnet nodes - ETA: 07/26/2021
+
+- [ ] Periodically check the rollout status of v1.x.y and ping the community - ETA: 08/02/2021
+
diff --git a/.gitignore b/.gitignore
index b698caca93..ab135a3a38 100644
--- a/.gitignore
+++ b/.gitignore
@@ -13,7 +13,6 @@
 pprof*
 
 # Binaries for programs and plugins
-*.a
 *.exe
 *.dll
 *.dylib
@@ -35,8 +34,8 @@ data/*
 
 # binary
 bin/*
-*/release
+**/release
 coverage.txt
-*.log
+lint.log
 .editorconfig

**Comment by Newman1515** [comment]
From 7ff5364989e7d75f155069908025335432b92c04 Mon Sep 17 00:00:00 2001
From: Francisco A  Rivera <100412339+Newman1515@users.noreply.github.com>
Date: Fri, 27 May 2022 14:44:52 -0700
Subject: [PATCH] Revert "update issue template (#3414)"

This reverts commit 06d20211bdfc262b66474033c00b4c06c25c08fa.
---
 .github/ISSUE_TEMPLATE/bug_report.md   | 11 ++++++-
 .github/ISSUE_TEMPLATE/enhancement.md  | 13 ++------
 .github/ISSUE_TEMPLATE/failing-test.md | 22 ++++++++++++++
 .github/ISSUE_TEMPLATE/feature.md      | 38 ------------------------
 .github/ISSUE_TEMPLATE/refactor.md     | 21 -------------
 .github/ISSUE_TEMPLATE/rollout.md      | 41 ++++++++++++++++++++++++++
 .gitignore                             |  5 ++--
 7 files changed, 78 insertions(+), 73 deletions(-)
 create mode 100644 .github/ISSUE_TEMPLATE/failing-test.md
 delete mode 100644 .github/ISSUE_TEMPLATE/feature.md
 delete mode 100644 .github/ISSUE_TEMPLATE/refactor.md
 create mode 100644 .github/ISSUE_TEMPLATE/rollout.md

diff --git a/.github/ISSUE_TEMPLATE/bug_report.md b/.github/ISSUE_TEMPLATE/bug_report.md
index 6eab5d496e..2d56d3e48e 100644
--- a/.github/ISSUE_TEMPLATE/bug_report.md
+++ b/.github/ISSUE_TEMPLATE/bug_report.md
@@ -4,16 +4,25 @@ about: Create a bug report to help us improve
 title: ''
 labels: bug
 assignees: ''
+
 ---
 
 
 
-### What version of iotex-core image (or code branch) are you using?
+### What version of iotex-core are you using (`ioctl version`)?
+
+
 
 ### What operating system and processor architecture are you using?
 
+
+
 ### What did you do? If possible, provide a recipe for reproducing the error.
 
+
+
 ### What did you expect to see?
 
+
+
 ### What did you see instead?
diff --git a/.github/ISSUE_TEMPLATE/enhancement.md b/.github/ISSUE_TEMPLATE/enhancement.md
index 31247e0352..e73d216a51 100644
--- a/.github/ISSUE_TEMPLATE/enhancement.md
+++ b/.github/ISSUE_TEMPLATE/enhancement.md
@@ -4,18 +4,11 @@ about: Suggest an enhancement to iotex-core project
 title: ''
 labels: enhancement
 assignees: ''
+
 ---
 
 
 
-### What would you like to be added
-
-### Why is this needed
-
-### How important you think this is for IoTeX
-- [] must have
-- [] should have
-- [] nice to have
+**What would you like to be added**:
 
-### Additional information
-Let us know any background or context that would help us better understand the request (for example the particular use-case that prompted this request)
\ No newline at end of file
+**Why is this needed**:
diff --git a/.github/ISSUE_TEMPLATE/failing-test.md b/.github/ISSUE_TEMPLATE/failing-test.md
new file mode 100644
index 0000000000..bba8f3bd56
--- /dev/null
+++ b/.github/ISSUE_TEMPLATE/failing-test.md
@@ -0,0 +1,22 @@
+---
+name: Failing Test
+about: Report test failures in iotex-core CI jobs
+title: ''
+labels: test
+assignees: ''
+
+---
+
+
+
+**Which jobs are failing**:
+
+**Which test(s) are failing**:
+
+**Since when has it been failing**:
+
+**Testgrid link**:
+
+**Reason for failure**:
+
+**Anything else we need to know**:
diff --git a/.github/ISSUE_TEMPLATE/feature.md b/.github/ISSUE_TEMPLATE/feature.md
deleted file mode 100644
index f06d30e038..0000000000
--- a/.github/ISSUE_TEMPLATE/feature.md
+++ /dev/null
@@ -1,38 +0,0 @@
----
-name: Feature Request
-about: New feature request to iotex-core project
-title: ''
-labels: feature
-assignees: ''
----
-
-
-
-### Description of new feature request
-
-### Is this a hard-fork (and height to be activated)
-- [] Yes
-- Name of activation height:
-
-### Implementation plan
-- [] Phase 1 description (PR number)
-- [] Phase 2 description (PR number)
-- [] Phase 3 description (PR number)
-
-### Affected modules
-- [] action
-- [] actpool
-- [] api
-- [] blockchain
-- [] blockindex
-- [] blocksync
-- [] chainservice
-- [] config
-- [] consensus
-- [] db
-- [] dispatcher
-- [] ioctl
-- [] p2p
-- [] server
-- [] state
-- [] tools
diff --git a/.github/ISSUE_TEMPLATE/refactor.md b/.github/ISSUE_TEMPLATE/refactor.md
deleted file mode 100644
index bc015b6ae9..0000000000
--- a/.github/ISSUE_TEMPLATE/refactor.md
+++ /dev/null
@@ -1,21 +0,0 @@
----
-name: Code refactor
-about: File a code refactor task
-title: ''
-labels: refactor
-assignees: ''
----
-
-
-
-### Description of the code refactor
-
-### Why is this needed
-- [] better/less memory usage
-- [] reduce running time
-- [] clean (easy-to-understand) data structure or algorithm
-- [] remove dead code
-- [] better code design or structure (like reduce complexity)
-- [] reduce/decouple dependencies between code modules
-- [] increase test coverage
-- [] better code readability
diff --git a/.github/ISSUE_TEMPLATE/rollout.md b/.github/ISSUE_TEMPLATE/rollout.md
new file mode 100644
index 0000000000..94dc48858e
--- /dev/null
+++ b/.github/ISSUE_TEMPLATE/rollout.md
@@ -0,0 +1,41 @@
+---
+name: Rollout Request
+about: Create an issue to track the rollout of a new release
+title: ''
+labels: rollout
+assignees: ''
+
+---
+
+**If you hit a critical issue which needs a new release candidate** while completing steps below: 
+1. file another issue for the critical issue
+2. close the current task with the critical issue just filed
+3. fix the critical issue
+4. and file another rollout request to track v1.x.y-rc1
+
+**Rollout Steps**
+
+- [ ] Cut release v1.x.y-rc0 - ETA: 06/28/2021
+
+- [ ] Rollout v1.x.y-rc0 to testnet - ETA: 06/28/2021
+
+- [ ] Stress test v1.x.y-rc0 on testnet - ETA: 07/05/2021
+
+- [ ] Hit critical problems (close this task and file another one to track v1.x.y-rc1)
+
+- [ ] Rollout v1.x.y-rc0 to canary API nodes on mainnet - ETA: 07/12/2021
+
+- [ ] Promote release candidate v1.x.y-rc0 to be v1.x.y - ETA: 07/19/2021
+
+- [ ] Submit release notes to https://github.com/iotexproject/iotex-bootstrap/tree/master/changelog - ETA: 07/19/2021
+
+- [ ] Update https://github.com/iotexproject/iotex-bootstrap/blob/master/README.md - ETA: 07/19/2021
+
+- [ ] Notify the community (delegates, exchanges and wallets) - ETA: 07/19/2021
+
+- [ ] Rollout v1.x.y to testnet and all canary nodes on mainnet - ETA: 07/19/2021
+
+- [ ] Rollout v1.x.y to our mainnet nodes - ETA: 07/26/2021
+
+- [ ] Periodically check the rollout status of v1.x.y and ping the community - ETA: 08/02/2021
+
diff --git a/.gitignore b/.gitignore
index b698caca93..ab135a3a38 100644
--- a/.gitignore
+++ b/.gitignore
@@ -13,7 +13,6 @@
 pprof*
 
 # Binaries for programs and plugins
-*.a
 *.exe
 *.dll
 *.dylib
@@ -35,8 +34,8 @@ data/*
 
 # binary
 bin/*
-*/release
+**/release
 coverage.txt
-*.log
+lint.log
 .editorconfig

**Review by Newman1515 — COMMENTED** [review]
submit the approve

**Pull request closed without merging**
