### PR TITLE
Updated PutIfNotExists method for memory kv to make it safe for concurrent use

### PR DESCRIPTION
**Pull request by coldhiber**
Improved PutIfNotExists for memory store to make it safe for concurrent use. The new implementation uses PutIfNotExists method from the syncmap which performs atomic insert.

Details about the LoadOrStore method - https://godoc.org/golang.org/x/sync/syncmap#Map.LoadOrStore

(this PR is working copy of the broken PR #13)

### CODE REVIEW

**Comment by coldhiber** [comment]
@zjshen14 rebased onto master

**Comment by coldhiber** [comment]
@dustinxie @zjshen14 sorry guys, I've broken the last branch (PR #13) by the incorrect actions with rebase and PR was automatically closed. Recreated it again here

**Comment by zjshen14** [comment]
It seems that CI is still not working properly for the PR from the forked branch. @Zhen-iotex, any idea why the shared crypto library is not found: https://circleci.com/gh/iotexproject/iotex-core/155

**Comment by zjshen14** [comment]
@coldhiber i merged your PR. Thanks for the contribution

**Pull request merged**
