### PR TITLE
IOTEX-391 Solve the linux libsect283k1_ubuntu.so error and support windows

### PR DESCRIPTION
**Pull request by Frankonly**
ec283.go who needs libsect283k1_ubuntu.so is not used by our code but included in the crypto package, so I take away ec283.go and related test files from the crypto package and put them into a package that no files import. Therefore, we don't need libsect283k1_ubuntu and to export LD_LIBRARY_PATH now.

After moving these code, I try running the iotex-core in windows. reinstall gcc and restart the computer. New code can work on windows now. The way I tested on windows was `go build` in \server and then `./server.exe` to run. The server was running and producing blocks.

### CODE REVIEW

**Comment by zjshen14** [comment]
Can you describe why it will fix the problem?

**Comment by Frankonly** [comment]
> Can you describe why it will fix the problem?

if I use string “poll“ rather than poll.ProtocolID in nodedelegate.go, in which case “poll” should not be imported, ioctl can be executed without libsect283k1_ubuntu.so in linux, which means golang compiler packages all imported lib into binary. The ec283.go and related test files are not used by our code but packaged into binary due to importing the "crypto", so when I take away those idle code from crypt, the binary doesn't need the libsect283k1_ubuntu.so anymore.

**Comment by CoderZhi** [comment]
I guess the lib directory didn't have a go file and was ignored. After moving one go file into it, the directory will be included automatically

**Comment by zjshen14** [comment]
I still couldn't understand why we used not to need libsect283k1_ubuntu.so PREVIOUSLY. ioctl uses keystore, which uses crypto, which SHOULD use libsect283k1_ubuntu.so for signature eventually.

It found geth has signature_cgo.go and signature_nocgo.go. The latter uses a pure golang implementation. Did you somehow build ioctl and use signature_nocgo.go in the end, so that libsect283k1_ubuntu.so is not required before?

**Comment by Frankonly** [comment]
> I still couldn't understand why we used not to need libsect283k1_ubuntu.so PREVIOUSLY. ioctl uses keystore, which uses crypto, which SHOULD use libsect283k1_ubuntu.so for signature eventually.
> 
> It found geth has signature_cgo.go and signature_nocgo.go. The latter uses a pure golang implementation. Did you somehow build ioctl and use signature_nocgo.go in the end, so that libsect283k1_ubuntu.so is not required before?

ioctl account use the keystore who imports crypto from go-ethereum rather than ours. As what you say, it is a pure golang implementation.

**Comment by Frankonly** [comment]
#941 #801

**Pull request merged**
