### PR TITLE
Moved test/util to the testutil folder

### PR DESCRIPTION
**Pull request by coldhiber**
Moved test/util to the testutil folder according to the #22

### CODE REVIEW

**Comment by coldhiber** [comment]
@zjshen14 ops, sorry, missed that. Done.

**Comment by zjshen14** [comment]
@coldhiber when merging, please use "squash and merge" option. Thanks!

**Comment by coldhiber** [comment]
@lizhefeng merge button is not enabled for me. Could you please merge it?

**Comment by zjshen14** [comment]
@coldhiber, can you check if the license/cla check is green for you already, if not, please sign the agreement first.

screen shot 2018-07-25 at 1 12 38 pm

**Comment by lizhefeng** [comment]
@coldhiber Can you please rebase this PR onto the latest master? Thanks!

**Comment by coldhiber** [comment]
@lizhefeng I think it's already up to date. Last commit is https://github.com/iotexproject/iotex-core/commit/6c2d0a2636bc2d4ee77a6ba4f53e68d24d74a7d8. The same in the current PR.

**Comment by lizhefeng** [comment]
@coldhiber This PR failed on CI. It seems to be the problem of your last commit 2fba556b035384f2dd5609442d45a73c2a0e1a5a. Can you please revert this commit and rebase this PR onto the latest master, resolve conflicts, and then push it again?

**Comment by coldhiber** [comment]
@lizhefeng got it. Fixed. Done.

**Pull request merged**
