### PR TITLE
Return an error if the BoltDB hasn't started yet

### LINKED ISSUE #2928: [db] method should return error when db hasn't started
### What did you do? If possible, provide a recipe for reproducing the error.
https://github.com/iotexproject/iotex-core/blob/master/db/db_bolt.go#L80
b.db is nil when db hasn't started

### What did you expect to see?
when b.db is nil, an error should be directly returned
```
if b.db == nil {
return nil, errors.New("db hasn't started")
}
b.db.xxx
```

### What did you see instead?
null pointer panic

### PR DESCRIPTION
**Pull request by pocockn**
fix #2928 

Instead of panicking if the DB hasn't started yet, return an error

### CODE REVIEW

**Comment by pocockn** [comment]
https://github.com/iotexproject/iotex-core/issues/2928

**Comment by Liuhaai** [comment]
thx for contributing. Does pointer check need to be added at https://github.com/iotexproject/iotex-core/blob/f1aa156608feda301d93e637dd480b2a761247bd/db/db_bolt.go#L226

**Comment by Liuhaai** [comment]
FYI, there are some keywords that can be used to link the issue 
https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by pocockn** [comment]
> FYI, there are some keywords that can be used to link the issue 
> https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

Great, thanks.

**Comment by pocockn** [comment]
Fixes iotexproject/iotex-core#2928

**Comment by pocockn** [comment]
> thx for contributing. Does pointer check also need to be added at
> 
> https://github.com/iotexproject/iotex-core/blob/f1aa156608feda301d93e637dd480b2a761247bd/db/db_bolt.go#L226

Added. Cheers!

**Review by Liuhaai — APPROVED** [review]

**Review by CoderZhi — APPROVED** [review]

**Pull request merged**
