### PR TITLE
[api] Move generateBlockMeta to grpcserver.go

### PR DESCRIPTION
**Pull request by LuckyPigeon**
# Description

Move `generateBlockMeta` to `grpcserver.go`

Fixes [# 3271](https://github.com/iotexproject/iotex-core/issues/3271)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] TestGrpcServer_GetBlockMetasIntegrity
- [x] TestGrpcServer_GetBlockMetaIntegrity

**Test Configuration**:

- Firmware version: Ubuntu 21.04
- Hardware:
- Toolchain:
- SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Liuhaai** [comment]
this pr is to be reviewed after https://github.com/iotexproject/iotex-core/pull/3298 is merged

**Comment by LuckyPigeon** [comment]
@Liuhaai 
Sure!

**Comment by Liuhaai** [comment]
> @Liuhaai Sure!

you could remove the `pending` label when the pr is ready for review

**Comment by LuckyPigeon** [comment]
Seems `generateBlockMeta` has already moved to `grpcserver.go`.

**Comment by Liuhaai** [comment]
> @Liuhaai Seems `generateBlockMeta` has already moved to `grpcserver.go`. BTY, I have no authority to remove `pending` tag.

could you give a link to  `generateBlockMeta`?

**Comment by LuckyPigeon** [comment]
Here you go
https://github.com/iotexproject/iotex-core/blob/682bad60d4d358b7d2bfc4add1f54a9c72a1b9ee/api/grpcserver.go#L727

**Comment by Liuhaai** [comment]
> remove BlockMeta from coreservice

`BlockMeta` in coreservice should be removed to solve this issue as well

**Comment by LuckyPigeon** [comment]
Both `BlockMetas` and `BlockMetaByHash` seems necessary to`coreservice.go`, and they both rely on `generateBlockMeta`, so I think there might be no func to remove.

**Comment by Liuhaai** [comment]
> Both `BlockMetas` and `BlockMetaByHash` seems necessary to`coreservice.go`, and they both rely on `generateBlockMeta`, so I think there might be no func to remove. Unless we need to combine them with `generateBlockMeta`.

ok, thx for the pr. I will complete remaining work in the following pr.

**Review by Liuhaai — APPROVED** [review]

**Review by dustinxie — APPROVED** [review]

**Pull request merged**
