### PR TITLE
Modify ReadContract API

### PR DESCRIPTION
**Pull request by lizhefeng**

### CODE REVIEW

**Comment by zjshen14** [comment]
@ququzone how urgent/critical is this issue to unblock the antenna?

**Comment by ququzone** [comment]
> @ququzone how urgent/critical is this issue to unblock the antenna?

not urgent, We can set gas manual.

**Comment by zjshen14** [comment]
@ququzone can you check if the change here makes sense to antena integration?

**Comment by ququzone** [comment]
> @ququzone can you check if the change here makes sense to antena integration?

how can I get executed normal method result by this way?

**Comment by zjshen14** [comment]
Return data structure will be the same, but the request Paramus become execution plus caller addr @lizhefeng

**Pull request closed without merging**
