### PR TITLE
Renamed miners to producers

### PR DESCRIPTION
**Pull request by coldhiber**
Renamed miners to producers according to the #20.

### CODE REVIEW

**Comment by coldhiber** [comment]
@lizhefeng renamed miners to producers. Let me know if you think that `blockProducer` would be better than `producer`.

**Comment by lizhefeng** [comment]
@coldhiber Can you please rebase this PR onto the latest master. Thanks!

**Comment by coldhiber** [comment]
@lizhefeng done

**Comment by lizhefeng** [comment]
@coldhiber Please resolve conflicts and push again. Thanks!

**Comment by coldhiber** [comment]
@lizhefeng done

**Pull request merged**
