### PR TITLE
[api]fix JsonRPC api response id type doesn't match request type

### LINKED ISSUE #4154: JsonRPC api response type doesn't match request type
### What did you do? If possible, provide a recipe for reproducing the error.

JsonRPC api response's `id` field type doesn't match the request type.

### Request

```
curl -X POST https://babel-api.mainnet.iotex.io -H "Content-Type:application/json" --data '{
    "jsonrpc":"2.0",
                "method":"eth_getTransactionCount",
                "params":["0x002E983C3134Cf7e7b0F2A3852fb66Faa34a5062", "latest"],
    "id": "1"
}'
```

### Response

```
{
 "jsonrpc":"2.0",
  "id":1, 
  "result":"0x0"
}
```

The `id` field's type should be `string`, not `number`. It's should be match the request type.

### PR DESCRIPTION
**Pull request by millken**
# Description
The id field's type should be match the request type.
if request id is `string`, the response id should be `string`, if request id is `number`, the response id should be `number` too.

Fixes #4154 

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Liuhaai** [comment]
what type does id use in geth?

**Comment by millken** [comment]
> what type of id is used in geth?
json.RawMessage

**Review by envestcc — APPROVED** [review]
need to add tests

**Comment by Liuhaai** [comment]
> > what type of id is used in geth?
> 
> json.RawMessage, It also gets the id from the request, checks if the id is valid (not an object or array), and returns it as it is

Could `any` be replaced with `json.RawMessage` type?

**Review by dustinxie — APPROVED** [review]

**Pull request merged**
